sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Zwq12345!
  alioss:
    endpoint: oss-ap-southeast-2.aliyuncs.com
    access-key-id: LTAI5tES4LLCM9HVF4CoNy5d
    access-key-secret: FrtrSYc4wc93QhBBkqovo7uRUrC96c
    bucket-name: lerbon-james-java
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  wechat:
    appid: wx7a6e950163e59cfa
    secret: 54de661f0ebef016de8d468c0d38ea71